services:
  - type: web
    name: blockchain-benchmark
    env: node
    plan: free
    repo: https://github.com/hiuoiiiubioiii/blockchain-caliper-benchmark
    buildCommand: npm install
    startCommand: npm start
